/// <reference types="cypress" />

import { should } from "chai"

describe('Amazon Shopping Cart Test Suite', function(){

it('1.Verify that the shopping cart button is visible on the product display page', function(){
    cy.visit('https://www.amazon.com/')
    cy.get('.nav-cart-icon').should('be.visible')

})
it('2.Verify that adding one item to the cart increases the quantity of the product', function(){
    cy.visit('https://www.amazon.com/')
    cy.get('#twotabsearchtextbox').type('Pen')
    cy.get('#nav-search-submit-button').click()
    cy.get('#nav-cart-count').contains('0')
    cy.get('[data-asin="B0B45RTFQH"] > .sg-col-inner > .s-widget-container > .s-card-container > .a-spacing-base > .s-product-image-container > .rush-component > .a-link-normal > .a-section > .s-image').click({ force: true })
    cy.get('#add-to-cart-button').click()  
    cy.get('#nav-cart-count').contains('1')
})

it('3.Verify that adding the same item to the cart increases the quantity', function(){
    cy.visit('https://www.amazon.com/')
    cy.get('#twotabsearchtextbox').type('Pen')
    cy.get('#nav-search-submit-button').click()
    cy.get('#nav-cart-count').contains('0')
    cy.get('[data-asin="B0B45RTFQH"] > .sg-col-inner > .s-widget-container > .s-card-container > .a-spacing-base > .s-product-image-container > .rush-component > .a-link-normal > .a-section > .s-image').click({ force: true })
    cy.get('#add-to-cart-button').click()  
    cy.get('#nav-cart-count').contains('1')
    cy.get('#sw-gtc > .a-button-inner > .a-button-text').click()
    cy.get('.a-dropdown-prompt').click()
    cy.get('#quantity_2').click()
    cy.get('#sc-subtotal-label-buybox').contains('2')
})

it('4.Verify that removing some items from the cart decreases the quantity of the cart', function(){
    cy.visit('https://www.amazon.com/')
    cy.get('#twotabsearchtextbox').type('Pen')
    cy.get('#nav-search-submit-button').click()
    cy.get('#nav-cart-count').contains('0')
    cy.get('[data-asin="B0B45RTFQH"] > .sg-col-inner > .s-widget-container > .s-card-container > .a-spacing-base > .s-product-image-container > .rush-component > .a-link-normal > .a-section > .s-image').click({ force: true })
    cy.get('#add-to-cart-button').click()  
    cy.get('#nav-cart-count').contains('1')
    cy.get('#sw-gtc > .a-button-inner > .a-button-text').click()
    cy.get('.a-dropdown-prompt').click()
    cy.get('#quantity_9').click()
    cy.get('#sc-subtotal-label-buybox').contains('9')
    cy.get('.sc-action-delete > .a-declarative > .a-color-link').click()
    cy.get('#sc-subtotal-label-activecart').contains('0')
})
it('5.Verify that when the user removes all items from the cart, the cart is displayed as empty', function(){
    cy.visit('https://www.amazon.com/')
    cy.get('#twotabsearchtextbox').type('Pen')
    cy.get('#nav-search-submit-button').click()
    cy.get('#nav-cart-count').contains('0')
    cy.get('[data-asin="B0B45RTFQH"] > .sg-col-inner > .s-widget-container > .s-card-container > .a-spacing-base > .s-product-image-container > .rush-component > .a-link-normal > .a-section > .s-image').click({ force: true })
    cy.get('#add-to-cart-button').click()  
    cy.get('#nav-cart-count').contains('1')
    cy.get('#sw-gtc > .a-button-inner > .a-button-text').click()
    cy.get('.a-dropdown-prompt').click()
    cy.get('#quantity_9').click()
    cy.get('#sc-subtotal-label-buybox').contains('9')
    cy.get('.sc-action-delete > .a-declarative > .a-color-link').click()
    cy.get('.a-row > .a-spacing-mini').should('be.visible')
})
it('6.Verify that the count of the cart changes when the user adds an item to the cart', function(){
    cy.visit('https://www.amazon.com/')
    cy.get('#twotabsearchtextbox').type('Pen')
    cy.get('#nav-search-submit-button').click()
    cy.get('#nav-cart-count').contains('0')
    cy.get('[data-asin="B0B45RTFQH"] > .sg-col-inner > .s-widget-container > .s-card-container > .a-spacing-base > .s-product-image-container > .rush-component > .a-link-normal > .a-section > .s-image').click({ force: true })
    cy.get('#add-to-cart-button').click()  
    cy.get('#nav-cart-count').contains('1')
    cy.get('#sw-gtc > .a-button-inner > .a-button-text').click()
    cy.get('.a-dropdown-prompt').click()
    cy.get('#quantity_9').click()
    cy.get('#sc-subtotal-label-buybox').contains('9')
    cy.get('#a-autoid-11 > .a-button-inner > .a-button-input').click()
    cy.get('#sw-gtc > .a-button-inner > .a-button-text').click()
    cy.get('#sc-subtotal-label-activecart').contains('10')    
})
it('7.Verify that clicking on a product in the shopping cart redirects the user to the product detail page', function(){
    cy.visit('https://www.amazon.com/')
    cy.get('#twotabsearchtextbox').type('Pen')
    cy.get('#nav-search-submit-button').click()
    cy.get('#nav-cart-count').contains('0')
    cy.get('[data-asin="B0B45RTFQH"] > .sg-col-inner > .s-widget-container > .s-card-container > .a-spacing-base > .s-product-image-container > .rush-component > .a-link-normal > .a-section > .s-image').click({ force: true })
    cy.get('#add-to-cart-button').click()  
    cy.get('#nav-cart-count').contains('1')
    cy.get('#sw-gtc > .a-button-inner > .a-button-text').click()
    cy.get('.a-dropdown-prompt').click()
    cy.get('#quantity_9').click()
    cy.get('#sc-subtotal-label-buybox').contains('9')
    cy.get('#a-autoid-11 > .a-button-inner > .a-button-input').click()
    cy.get('#sw-gtc > .a-button-inner > .a-button-text').click()
    cy.get('#sc-subtotal-label-activecart').contains('10')   
    cy.visit('https://www.amazon.com/gp/product/B09C43VSY4/ref=ox_sc_act_image_1?smid=A2LAY1OU4F0QFA&psc=1')
    })
it('8.Verify that clicking on the checkout button redirects the user to the checkout page', function(){
    cy.visit('https://www.amazon.com/')
    cy.get('#twotabsearchtextbox').type('Pen')
    cy.get('#nav-search-submit-button').click()
    cy.get('#nav-cart-count').contains('0')
    cy.get('[data-asin="B0B45RTFQH"] > .sg-col-inner > .s-widget-container > .s-card-container > .a-spacing-base > .s-product-image-container > .rush-component > .a-link-normal > .a-section > .s-image').click({ force: true })    
    cy.get('#add-to-cart-button').click()  
    cy.get('#nav-cart-count').contains('1')
    cy.get('#sc-buy-box-ptc-button > .a-button-inner > .a-button-input').click()  
    //Could't proceed to the checkout page due to lack of creditials  
    })
it('9.Verify that the total price is updated when a product is added to the cart', function(){
    cy.visit('https://www.amazon.com/')
    cy.get('.nav-cart-icon').click({force: true})
    cy.get('.a-span8 > .a-row > h2').contains('empty')
    cy.get('#twotabsearchtextbox').type('Pen')
    cy.get('#nav-search-submit-button').click()
    cy.get('#nav-cart-count').contains('0')
    cy.get('[data-asin="B0B45RTFQH"] > .sg-col-inner > .s-widget-container > .s-card-container > .a-spacing-base > .s-product-image-container > .rush-component > .a-link-normal > .a-section > .s-image').click({ force: true })
    cy.get('#add-to-cart-button').click()  
    cy.get('#nav-cart-count').contains('1')
    cy.get('#sw-gtc > .a-button-inner > .a-button-text').click()
    cy.get('#sc-subtotal-amount-buybox > .a-size-medium').contains('$8.89')
    })
it('10.Verify that the total price is reduced when a product is removed from the cart', function(){
    cy.visit('https://www.amazon.com/')
    cy.get('.nav-cart-icon').click({force: true})
    cy.get('.a-span8 > .a-row > h2').contains('empty')
    cy.get('#twotabsearchtextbox').type('Pen')
    cy.get('#nav-search-submit-button').click()
    cy.get('#nav-cart-count').contains('0')
    cy.get('[data-asin="B0B45RTFQH"] > .sg-col-inner > .s-widget-container > .s-card-container > .a-spacing-base > .s-product-image-container > .rush-component > .a-link-normal > .a-section > .s-image').click({ force: true })
    cy.get('#add-to-cart-button').click()  
    cy.get('#nav-cart-count').contains('1')
    cy.get('#sw-gtc > .a-button-inner > .a-button-text').click()
    cy.get('#sc-subtotal-amount-buybox > .a-size-medium').contains('$8.89')
    cy.get('.sc-action-delete > .a-declarative > .a-color-link').click()
    cy.get('#sc-subtotal-amount-activecart > .a-size-medium').contains('$0.00')
    })
it('11.Verify that the products in the shopping cart remain the same even after the user refreshes the browser page', function(){
    cy.visit('https://www.amazon.com/')
    cy.get('.nav-cart-icon').click({force: true})
    cy.get('.a-span8 > .a-row > h2').contains('empty')
    cy.get('#twotabsearchtextbox').type('Pen')
    cy.get('#nav-search-submit-button').click()
    cy.get('[data-asin="B0B45RTFQH"] > .sg-col-inner > .s-widget-container > .s-card-container > .a-spacing-base > .s-product-image-container > .rush-component > .a-link-normal > .a-section > .s-image').click({ force: true })
    cy.get('#add-to-cart-button').click()  
    cy.get('#sw-gtc > .a-button-inner > .a-button-text').click()
    cy.get('#sc-active-cart > .a-cardui-body').contains('Gel Pens')
    cy.reload()
    cy.get('#sc-active-cart > .a-cardui-body').contains('Gel Pens')
    })
    
   



    


   
})
